### ISSUE TITLE
refactor : GroupMember role에 OWNER 추가

### ISSUE THREAD

**Issue by rladmstn** [GAMZA-BAT/ALGOHUB-SERVER#103]
## 📌 Issue

🚨 대형 공사가 있을 예정입니다 🚨
볼륨 더 커지기 전에 GroupMember에 방장인 OWNER를 추가할 예정입니다. 꼼꼼하게 작업하고자 하니 조금 시간이 걸려도.. 양해 부탁드립니다..

## ✅ TODO

- [x] OWNER 추가

**Comment by hwangjokim** [comment]
단순 노가다면 기반 다져놓고, 브랜치 공유해서 각자 파일 나눠서 수정하는 것도 좋을 것 같아요~ 물론 결정권은 서버파트장인 님에게 있습니다..

**Comment by rladmstn** [comment]
> 단순 노가다면 기반 다져놓고, 브랜치 공유해서 각자 파일 나눠서 수정하는 것도 좋을 것 같아요~ 물론 결정권은 서버파트장인 님에게 있습니다..

지금 있는 PR 다 머지 되고 한 번 어느정도 규모로 수정되어야 하는지 보려구요! 혼자 커버하기 무리 없을 것 같으면 이번 PR에서 모두 진행하고 아니면 각자 파일에서 수정하고자 합니다-
