### ISSUE TITLE
fix : 그룹 목록 조회 시 주인이어도 isOwner가 false로 발생하는 버그 수정

### ISSUE THREAD

**Issue by rladmstn** [GAMZA-BAT/ALGOHUB-SERVER#108]
## 📌 Issue

제가 `GroupMember`에 `OWNER` 추가하는 리팩토링을 진행하면서, 방장 여부를 boolean으로 리턴할 때 객체 참조 비교로 써버렸습니다..
테스트 코드에서 왜 안잡혔나 보니 제가 테스트 할 때 `isOwner`를 검증 안 했을 뿐더러, 했더라도 테스트 내에서의 동일한 user 객체를 사용해서 참조 비교를 사용했어도 검증에 통과하지 않았을까 싶습니다. 

```java
public static GetStudyGroupResponse toDTO(StudyGroup group, User user, boolean isBookmarked, User owner) {
	return new GetStudyGroupResponse(
                ...
		owner.equals(user),
                ...
```

객체 참조여서 방장이어도 false로 나오는 버그 수정합니다. 

## ✅ TODO

- [x] `isOwner` 객체 참조 비교를 id 비교로 수정하기
- [x] `isOwner` 검증하는 테스트 추가하기

**Comment by sh0723** [comment]
객체 참조 비교로 써버려서 오류가 난다는 게 객체의 메모리 주소값을 비교해서 방장이어도 false로 나오는 것 맞나요?

**Comment by rladmstn** [comment]
> 객체 참조 비교로 써버려서 오류가 난다는 게 객체의 메모리 주소값을 비교해서 방장이어도 false로 나오는 것 맞나요?

네 맞습니다! 그렇게 표현하는게 더 명확할 것 같네요!

**Comment by sh0723** [comment]
> > 객체 참조 비교로 써버려서 오류가 난다는 게 객체의 메모리 주소값을 비교해서 방장이어도 false로 나오는 것 맞나요?
> 
> 네 맞습니다! 그렇게 표현하는게 더 명확할 것 같네요!

네넵 알겠슴다
