### ISSUE TITLE
refactor : 공지 작성 API 에 필드 추가 및 board->notice 로 수정하겠습니다 ..!

### ISSUE THREAD

**Issue by s-hwan** [GAMZA-BAT/ALGOHUB-SERVER#137]
## 📌 Issue

- 프론트에서 category 라는 필드가 필요하다고 해서 추가하겠습니다
- board -> notice로 바꿔달라고하셔서 더 볼륨 커지기전에 이번 이슈에 수정하겠습니다.
- 

## ✅ TODO

- [ ] board ->notice로 수정
- [ ] category필드 추가

**Comment by hwangjokim** [comment]
가져갑니다.
