### ISSUE TITLE
feat : 문제 별 풀이 검색 API 추가

### ISSUE THREAD

**Issue by sh0723** [GAMZA-BAT/ALGOHUB-SERVER#18]
## 📌 Issue
문제 별로 특정 문제에 대해 닉네임, 언어, 결과가 입력되면 해당되는 문제의 풀이를 리턴해주는 API 만들겠습니다~!
 
## ✅ TODO
닉네임으로 필터링 했을 경우
언어로 필터링 했을 경우
코드 결과로 필터링 했을 경우

**Comment by rladmstn** [comment]
이거 코드 결과 점수로 보여주기로 결정돼서 이제 진행 하셔도 될 것 같습니다! 우선 순위 올려주세욥

**Comment by sh0723** [comment]
네넵 알겠읍니다

**Comment by sh0723** [comment]
다시 시작하겠습니다... 좀 오래걸릴듯요
