### ISSUE TITLE
refactor : 풀이 조회 관련 API 엔드포인트 수정

### ISSUE THREAD

**Issue by rladmstn** [GAMZA-BAT/ALGOHUB-SERVER#32]
## 📌 Issue

풀이 목록 조회 API, 풀이 하나 조회 API의 엔드포인트가 각각 /api/solution/solutions, /api/solution/solution 으로 되어 있더라구요 더 나은 엔드포인트를 위해,, 수정하려 합니다

## ✅ TODO

- [x] 풀이 조회 관련 API들 엔드포인트 수정

**Comment by hwangjokim** [comment]
좋네요.. solution/solution은 좀 끔찍해보이긴 합니다
