### ISSUE TITLE
ttttt

### ISSUE THREAD

**Issue by hwangjokim** [GAMZA-BAT/ALGOHUB-SERVER#34]
## 📌 Issue

Redis 연결이 안돼서 로그아웃이 정상적으로 작동하지 않는 오류가 있었습니다.

## ✅ TODO

- [ ] Redis 연동 fix

**Comment by rladmstn** [comment]
아!!!!! Redis yml 파일을 제가 localhost에서 수정을 안했네요 제삼다

**Comment by rladmstn** [comment]
이거 hoxy 실제 issue 인가요?

**Comment by hwangjokim** [comment]
아뇨이거 테스트용입니다.. 잠깐 뭐좀 해보고 Close 합니다

**Comment by rladmstn** [comment]
아하 알게ㅅ습니다
