### ISSUE TITLE
feat : 문제 삭제 API 추가

### ISSUE THREAD

**Issue by sh0723** [GAMZA-BAT/ALGOHUB-SERVER#47]
## 📌 Issue
문제 하나를 삭제하는 API추가

## ✅ TODO
문제 하나 삭제하는 API 추가할게욥!

**Comment by hwangjokim** [comment]
close 할 때 이유 간략하게 달고 close with comment 해주세용

**Comment by sh0723** [comment]
아 넵..! 사실 이 API가 이미 존재해서 닫았슴다 ㅎ,ㅎ
