### ISSUE TITLE
test : 그룸 멤버 전체 랭킹 API 추가

### ISSUE THREAD

**Issue by sh0723** [GAMZA-BAT/ALGOHUB-SERVER#58]
## 📌 Issue
테스트코드 작성하는 것 도전!

## ✅ TODO
해보겠읍니다..!

**Comment by rladmstn** [comment]
이거 똑같은 이슈 있던데 중복 아닌가요??

**Comment by sh0723** [comment]
어라라 그러네요 .. 안올라간줄알고 만들었는데 삭제하겠슴다!

**Comment by sh0723** [comment]
똑같은 이슈가 존재해서 닫습니다
