### ISSUE TITLE
feat: CI에서 린트 에러 잡도록

### ISSUE THREAD

**Issue by hwangjokim** [GAMZA-BAT/ALGOHUB-SERVER#64]
## 📌 Issue

다들 코드 포매터 적용한 것 같으니까, CI 단계에서 검증하도록 합니다.

**Comment by s-hwan** [comment]
궁금한게 코드 포매터를 적용했는데 저는 여전히 내 맘대로 작성하는데 알아서 포매팅이 된다는거죠..?

**Comment by hwangjo-v6x** [comment]
넵. 인텔리제이는 코드 창에서 포커스를 풀 때 (마우스로 다른 거 누를때) 자동저장하고, 동시에 포매터가 돕니다
그래서 알게 모르게 다 적용이 잘 되고 있습니다

**Comment by rladmstn** [comment]
> 넵. 인텔리제이는 코드 창에서 포커스를 풀 때 (마우스로 다른 거 누를때) 자동저장하고, 동시에 포매터가 돕니다 그래서 알게 모르게 다 적용이 잘 되고 있습니다

일하시는 계정에는 역시 잔디가 많이 깔려잇네요 잘 구경하고 갑니다

**Comment by hwangjokim** [comment]
계정실수 그만하고싶다

**Comment by hwangjokim** [comment]
쓰려는 라이브러리가 생각보다 너무 구려서 안합니다.
