### ISSUE TITLE
feat : 알림 발생 시 등록된 이메일로 메일 전송 

### ISSUE THREAD

**Issue by sh0723** [GAMZA-BAT/ALGOHUB-SERVER#70]
## 📌 Issue
알림 발생 시 깃헙처럼 메일 보내는 API 도전해보겠읍니다!

## ✅ TODO
- 알림 발송하는 송신자 이메일은 GMAIL로 제가 따로 만들겠습니다!

**Comment by sh0723** [comment]
서비스를 추가하는게 아니라 만들어져있는 send를 sendAndEmail로 수정할게요!

**Comment by rladmstn** [comment]
엇 근데 이거 알림은 우선 순위 좀 낮춰야 해요! 아직 알림 전송 자체도 미완인지라 이건 프론트까지 완벽하게 연동되면 나중에 합시다

**Comment by rladmstn** [comment]
이거 말고 방장 부방장한테 문제 Queued 카테고리 추가된거 먼저 해주실래요?

**Comment by sh0723** [comment]
넵 …!

**Comment by rladmstn** [comment]
담에 다시 엽시다
