### ISSUE TITLE
feat : 닉네임 중복 검사 API 추가 

### ISSUE THREAD

**Issue by rladmstn** [GAMZA-BAT/ALGOHUB-SERVER#88]
## 📌 Issue

닉네임 글자 수 제한 및 중복 검사 API를 추가합니다.

## ✅ TODO

- [ ] 닉네임 중복 검사 API 추가

**Comment by rladmstn** [comment]
할라 했는데 생각해보니까 닉네임 글자 수나 문자 제한 같은 상세 부분이 정해지지 않아, 4차 회의에서 논의하고 해당 이슈 진행합니다.

**Comment by rladmstn** [comment]
롤과 동일하게 ㅎㅎ 3글자 이상 16글자 이하 특수문자 불가로 진행합니다

**Comment by hwangjokim** [comment]
저희 디자인상 아이디, 비밀번호도 스펙있는데 따르나요?
![image](https://github.com/user-attachments/assets/8de0c8e6-170c-418b-8968-a5a9f7b485b1)

**Comment by rladmstn** [comment]
> 저희 디자인상 아이디, 비밀번호도 스펙있는데 따르나요? ![image](https://private-user-images.githubusercontent.com/96808859/364018374-8de0c8e6-170c-418b-8968-a5a9f7b485b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzMxMTQsIm5iZiI6MTcyNTM3MjgxNCwicGF0aCI6Ii85NjgwODg1OS8zNjQwMTgzNzQtOGRlMGM4ZTYtMTcwYy00MThiLTg5NjgtYTVhOWY3YjQ4NWIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE0MTMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMWI4NGE2ZWU1YzZkYjZkMDZjMWIxNDQ3OWIxODVkN2UyMzAwYmFkOGY1OTcwMmE0ZDE0NGI4M2VkN2E4NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EQkQuz_PhU6JIT3IUFhcQUydOMGjqBYuKJRnwlO_n0Y)

네 아이디는 이메일로 대체되니까 괜찮고 비밀번호만 저 제한 따르면 될 것 가타요

**Comment by hwangjokim** [comment]
옙 이 validation 프론트/백 둘다 진행하면 되겠네용
